### ISSUE TITLE
Edit vars by number instead of name

### ISSUE THREAD

**Issue by Loobinex** [JohnWeightman/Twitch-Chat-Stats#1]
Please allow users to reference variables by the index number instead of the full name. Saves typing.

E.G.: "[4] +2" would add 2 to the 4th variable listed.

**Comment by IstalriSkolir** [comment]
Feature has been added and tested, waiting to test on stream before closing ticket

**Comment by IstalriSkolir** [comment]
Testing during stream, passed test
